/**
 * @module commute-data
 */
export default [
    { name: 'Havard',                   type: 'Early Education', distance: 1.2, drive:  6, bike:  8 },
    { name: 'Serra Annex',              type: 'Early Education', distance: 1.6, drive:  7, bike: 15 },
    { name: 'McLaren',                  type: 'Early Education', distance: 2.7, drive:  9, bike: 22 },
    { name: 'Rodriguez',                type: 'Early Education', distance: 2.2, drive: 10, bike: 16 },
    { name: 'San Miguel',               type: 'Early Education', distance: 3.4, drive: 10, bike: 16 },
    { name: 'Mahler',                   type: 'Early Education', distance: 2.9, drive: 14, bike: 26 },
    { name: 'Weill',                    type: 'Early Education', distance: 5.1, drive: 14, bike: 32 },
    { name: 'Stockton',                 type: 'Early Education', distance: 5.5, drive: 18, bike: 38 },
    { name: 'Tule Elk Park',            type: 'Early Education', distance: 6.2, drive: 19, bike: 40 },
    { name: 'Jefferson',                type: 'Early Education', distance: 6.5, drive: 21, bike: 46 },
    { name: 'Noriega',                  type: 'Early Education', distance: 6.5, drive: 21, bike: 49 },
    { name: 'Argonne',                  type: 'Early Education', distance: 7.3, drive: 24, bike: 48 },

    { name: 'Drew',                     type: 'Elementary',      distance: 0.6, drive:  3, bike:  3 },
    { name: 'San Francisco',            type: 'Elementary',      distance: 0.7, drive:  4, bike:  4 },
    { name: 'Taylor',                   type: 'Elementary',      distance: 0.7, drive:  4, bike:  5 },
    { name: 'Alta Vista',               type: 'Elementary',      distance: 0.8, drive:  4, bike:  5 },
    { name: 'Meadows Livingstone',      type: 'Elementary',      distance: 1.5, drive:  5, bike:  8 },
    { name: 'Revere',                   type: 'Elementary',      distance: 1.2, drive:  5, bike:  9 },
    { name: 'Hillcrest',                type: 'Elementary',      distance: 1.1, drive:  5, bike: 10 },
    { name: 'El Dorado',                type: 'Elementary',      distance: 1.4, drive:  5, bike: 14 },
    { name: 'Carver',                   type: 'Elementary',      distance: 1.2, drive:  6, bike:  8 },
    { name: 'Bryant',                   type: 'Elementary',      distance: 1.7, drive:  6, bike: 10 },
    { name: 'Serra',                    type: 'Elementary',      distance: 1.6, drive:  6, bike: 14 },
    { name: 'Harte',                    type: 'Elementary',      distance: 1.5, drive:  7, bike:  8 },
    { name: 'KIPP Bayview',             type: 'Elementary',      distance: 1.5, drive:  7, bike:  9 },
    { name: 'Flynn',                    type: 'Elementary',      distance: 1.6, drive:  7, bike: 13 },
    { name: 'X',                        type: 'Elementary',      distance: 1.8, drive:  7, bike: 13 },
    { name: 'Monroe',                   type: 'Elementary',      distance: 1.8, drive:  7, bike: 15 },
    { name: 'Mission Preparatory',      type: 'Elementary',      distance: 2.0, drive:  8, bike: 12 },
    { name: 'Visitacion Valley',        type: 'Elementary',      distance: 2.2, drive:  8, bike: 14 },
    { name: 'SF Community',             type: 'Elementary',      distance: 1.9, drive:  8, bike: 15 },
    { name: 'King',                     type: 'Elementary',      distance: 2.1, drive:  8, bike: 16 },
    { name: 'Huerta',                   type: 'Elementary',      distance: 1.9, drive:  8, bike: 17 },
    { name: 'Glen Park',                type: 'Elementary',      distance: 2.6, drive:  8, bike: 18 },
    { name: 'Cleveland',                type: 'Elementary',      distance: 2.1, drive:  8, bike: 19 },
    { name: 'Carmichael',               type: 'Elementary',      distance: 3.4, drive:  8, bike: 21 },
    { name: 'Webster',                  type: 'Elementary',      distance: 2.8, drive:  9, bike: 22 },
    { name: 'Moscone',                  type: 'Elementary',      distance: 2.3, drive: 10, bike: 14 },
    { name: 'Mission Education Center', type: 'Elementary',      distance: 2.2, drive: 10, bike: 19 },
    { name: 'Sunnyside',                type: 'Elementary',      distance: 3.1, drive: 10, bike: 24 },
    { name: 'Chávez',                   type: 'Elementary',      distance: 2.3, drive: 11, bike: 15 },
    { name: 'Synergy',                  type: 'Elementary',      distance: 2.3, drive: 11, bike: 17 },
    { name: 'La Scuola',                type: 'Elementary',      distance: 2.8, drive: 11, bike: 17 },
    { name: 'Michiels',                 type: 'Elementary',      distance: 2.4, drive: 11, bike: 18 },
    { name: 'Longfellow',               type: 'Elementary',      distance: 4.1, drive: 11, bike: 26 },
    { name: 'Buena Vista Horace Mann',  type: 'Elementary',      distance: 2.5, drive: 12, bike: 17 },
    { name: 'St. James',                type: 'Elementary',      distance: 2.5, drive: 12, bike: 20 },
    { name: 'Marshall',                 type: 'Elementary',      distance: 3.3, drive: 12, bike: 20 },
    { name: 'Guadalupe',                type: 'Elementary',      distance: 3.0, drive: 12, bike: 24 },
    { name: 'French American Int\'l',   type: 'Elementary',      distance: 4.2, drive: 12, bike: 27 },
    { name: 'Ortega',                   type: 'Elementary',      distance: 5.1, drive: 12, bike: 33 },
    { name: 'Edison',                   type: 'Elementary',      distance: 2.8, drive: 13, bike: 22 },
    { name: 'SF Friends',               type: 'Elementary',      distance: 3.8, drive: 13, bike: 22 },
    { name: 'Tenderloin Community',     type: 'Elementary',      distance: 4.2, drive: 13, bike: 28 },
    { name: 'Alvarado',                 type: 'Elementary',      distance: 3.6, drive: 13, bike: 29 },
    { name: 'Miraloma',                 type: 'Elementary',      distance: 3.8, drive: 13, bike: 37 },
    { name: 'Sloat',                    type: 'Elementary',      distance: 4.8, drive: 14, bike: 31 },
    { name: 'Milk',                     type: 'Elementary',      distance: 3.9, drive: 15, bike: 29 },
    { name: 'Lakeshore',                type: 'Elementary',      distance: 5.7, drive: 15, bike: 35 },
    { name: 'West Portal',              type: 'Elementary',      distance: 4.7, drive: 15, bike: 37 },
    { name: 'Children\'s Day',          type: 'Elementary',      distance: 3.7, drive: 16, bike: 24 },
    { name: 'Redding',                  type: 'Elementary',      distance: 4.6, drive: 16, bike: 33 },
    { name: 'Rooftop',                  type: 'Elementary',      distance: 4.3, drive: 16, bike: 36 },
    { name: 'Clarendon',                type: 'Elementary',      distance: 4.8, drive: 16, bike: 43 },
    { name: 'Sanchez',                  type: 'Elementary',      distance: 3.6, drive: 17, bike: 26 },
    { name: 'Muir',                     type: 'Elementary',      distance: 4.5, drive: 17, bike: 32 },
    { name: 'Parks',                    type: 'Elementary',      distance: 5.0, drive: 17, bike: 33 },
    { name: 'McKinley',                 type: 'Elementary',      distance: 4.6, drive: 17, bike: 34 },
    { name: 'Creative Arts',            type: 'Elementary',      distance: 5.2, drive: 17, bike: 34 },
    { name: 'Yu',                       type: 'Elementary',      distance: 5.6, drive: 17, bike: 41 },
    { name: 'Sheridan',                 type: 'Elementary',      distance: 4.6, drive: 18, bike: 29 },
    { name: 'Lee',                      type: 'Elementary',      distance: 5.4, drive: 18, bike: 34 },
    { name: 'Chin',                     type: 'Elementary',      distance: 5.5, drive: 18, bike: 35 },
    { name: 'Spring Valley Science',    type: 'Elementary',      distance: 5.1, drive: 18, bike: 37 },
    { name: 'Sherman',                  type: 'Elementary',      distance: 5.4, drive: 18, bike: 39 },
    { name: 'Ulloa',                    type: 'Elementary',      distance: 6.3, drive: 18, bike: 40 },
    { name: 'Lau',                      type: 'Elementary',      distance: 5.2, drive: 19, bike: 34 },
    { name: 'Parker',                   type: 'Elementary',      distance: 5.6, drive: 19, bike: 36 },
    { name: 'Feinstein',                type: 'Elementary',      distance: 5.3, drive: 19, bike: 39 },
    { name: 'Grattan',                  type: 'Elementary',      distance: 5.2, drive: 19, bike: 43 },
    { name: 'Stevenson',                type: 'Elementary',      distance: 6.7, drive: 19, bike: 45 },
    { name: 'New School of SF',         type: 'Elementary',      distance: 5.5, drive: 20, bike: 38 },
    { name: 'De Avila',                 type: 'Elementary',      distance: 5.4, drive: 20, bike: 39 },
    { name: 'Garfield',                 type: 'Elementary',      distance: 5.7, drive: 20, bike: 39 },
    { name: 'Cobb',                     type: 'Elementary',      distance: 6.1, drive: 20, bike: 40 },
    { name: 'SF Public Montessori',     type: 'Elementary',      distance: 5.6, drive: 20, bike: 42 },
    { name: 'Jefferson',                type: 'Elementary',      distance: 6.3, drive: 20, bike: 44 },
    { name: 'Wo',                       type: 'Elementary',      distance: 5.5, drive: 21, bike: 39 },
    { name: 'New Traditions',           type: 'Elementary',      distance: 5.7, drive: 22, bike: 41 },
    { name: 'Sunset',                   type: 'Elementary',      distance: 7.4, drive: 22, bike: 46 },
    { name: 'Lawton',                   type: 'Elementary',      distance: 6.9, drive: 22, bike: 48 },
    { name: 'Peabody',                  type: 'Elementary',      distance: 7.2, drive: 23, bike: 49 },
    { name: 'Key',                      type: 'Elementary',      distance: 7.8, drive: 23, bike: 50 },
    { name: 'McCoppin',                 type: 'Elementary',      distance: 6.8, drive: 24, bike: 47 },
    { name: 'Lilienthal',               type: 'Elementary',      distance: 7.2, drive: 24, bike: 48 },
    { name: 'Lilienthal - Madison',     type: 'Elementary',      distance: 7.1, drive: 24, bike: 49 },
    { name: 'Sutro',                    type: 'Elementary',      distance: 7.6, drive: 24, bike: 50 },
    { name: 'Argonne',                  type: 'Elementary',      distance: 7.5, drive: 24, bike: 51 },
    { name: 'Alamo',                    type: 'Elementary',      distance: 8.1, drive: 26, bike: 54 },
    { name: 'Lafayette',                type: 'Elementary',      distance: 8.3, drive: 26, bike: 57 },

    { name: 'Brown',                    type: 'Middle',          distance: 0.4, drive:  1, bike:  3 },
    { name: 'King',                     type: 'Middle',          distance: 0.6, drive:  4, bike:  4 },
    { name: 'KIPP Bayview',             type: 'Middle',          distance: 1.3, drive:  6, bike: 10 },
    { name: 'Visitacion Valley',        type: 'Middle',          distance: 1.9, drive:  8, bike: 19 },
    { name: 'Denman',                   type: 'Middle',          distance: 3,   drive: 12, bike: 19 },
    { name: 'Lick',                     type: 'Middle',          distance: 2.8, drive: 13, bike: 23 },
    { name: 'Gateway',                  type: 'Middle',          distance: 5.2, drive: 16, bike: 35 },
    { name: 'Everett',                  type: 'Middle',          distance: 3.7, drive: 17, bike: 25 },
    { name: 'Aptos',                    type: 'Middle',          distance: 4.4, drive: 17, bike: 30 },
    { name: 'Hoover',                   type: 'Middle',          distance: 5.1, drive: 20, bike: 40 },
    { name: 'Roosevelt',                type: 'Middle',          distance: 6.8, drive: 26, bike: 47 },
    { name: 'Giannini',                 type: 'Middle',          distance: 7.1, drive: 26, bike: 44 },
    { name: 'Francisco',                type: 'Middle',          distance: 6.1, drive: 28, bike: 37 },
    { name: 'Marina',                   type: 'Middle',          distance: 6.5, drive: 30, bike: 43 },
    { name: 'Presidio',                 type: 'Middle',          distance: 8.1, drive: 33, bike: 56 },

    { name: 'Marshall',                 type: 'High',            distance: 0.2, drive:  1, bike:  3 },
    { name: 'Burton',                   type: 'High',            distance: 1.5, drive:  6, bike: 12 },
    { name: 'Downtown',                 type: 'High',            distance: 2.6, drive:  6, bike: 16 },
    { name: 'SF International',         type: 'High',            distance: 2.8, drive:  8, bike: 17 },
    { name: 'Jordan',                   type: 'High',            distance: 2.2, drive:  8, bike: 21 },
    { name: 'Balboa',                   type: 'High',            distance: 2.6, drive: 11, bike: 17 },
    { name: 'Asawa',                    type: 'High',            distance: 4.0, drive: 12, bike: 32 },
    { name: 'The Academy',              type: 'High',            distance: 3.8, drive: 11, bike: 31 },
    { name: 'O\'Connell',               type: 'High',            distance: 2.6, drive: 13, bike: 16 },
    { name: 'Wells',                    type: 'High',            distance: 4.8, drive: 13, bike: 37 },
    { name: 'Gateway',                  type: 'High',            distance: 5.4, drive: 15, bike: 36 },
    { name: 'Mission',                  type: 'High',            distance: 3.5, drive: 16, bike: 23 },
    { name: 'Independence',             type: 'High',            distance: 5.7, drive: 17, bike: 41 },
    { name: 'Lowell',                   type: 'High',            distance: 5.3, drive: 19, bike: 33 },
    { name: 'Lincoln',                  type: 'High',            distance: 5.8, drive: 23, bike: 45 },
    { name: 'Wallenberg',               type: 'High',            distance: 5.9, drive: 25, bike: 42 },
    { name: 'Washington',               type: 'High',            distance: 8.0, drive: 28, bike: 59 },
    { name: 'Galileo',                  type: 'High',            distance: 6.1, drive: 29, bike: 37 },
    { name: 'Life Learning',            type: 'High',            distance: 8.7, drive: 17, bike: 54 },
];
